config/routes.rb
Rails.application.routes.draw do
  resources :attendances
  resources :cards
  resources :profiles
  resources :courses
  root 'home#page'
  
  # request from canvas LTI
  post '/canvas', to: 'canvas#page'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/canvas_controller.rb
class CanvasController < ApplicationController

  def fetch_domain
    Rails.env == "development" ? Rails.application.credentials.domain[:dev] : Rails.application.credentials.domain[:production]
  end

  def create_course(course_params)
    if(!Course.exists?(:course_number => course_params[:course_number]))
      @course = Course.new(course_params)
      @course.save
    end
    # respond_to do |format|
    #   if @course.save 
    #       user_list = RestClient.get("https://coderacademy.instructure.com/api/v1/courses/#{course_id}/enrollments", headers= fetch_header)
    #       render json: user_list
    #       #  NOTE: the user list for the course can be stored in database. which holds user data -> name, sis id and email
    #   else
    #     format.json { render json: @course.errors, status: :unprocessable_entity }
    #   end
    # end
  end


  def create_profile(course_id)
    @course = Course.find_by(:course_number => course_id)
    enrollments = RestClient.get("https://coderacademy.instructure.com/api/v1/courses/#{course_id}/enrollments", headers= fetch_header)
    JSON.parse(enrollments.body).each do |enrollment|
      if(!Profile.exists?(user: enrollment["user"]))
        profile_params = {user: enrollment["user"], role: enrollment["role"]}
        @course.profiles.create(profile_params)
      end
    end
  end



   # NOTE : Token needs to be a canvas api key, which needs to be gerated by exporing developer keys on canvas, for now it is my account token
  def page
    uri = URI(params["launch_presentation_return_url"])
    # NOTE: update this code, instead of hardcoding the array position to fetch course id. build a logic to handle this
    course_id = uri.path.split('/')[2]

    # NOTE: update course database : Uncomment this later when Admin naviagtion is implemented
    course_name = params["context_title"]
    # fetch the course start and end date
    course = RestClient.get("https://coderacademy.instructure.com/api/v1/courses/#{course_id}", headers= fetch_header)
    puts "COURSE BODY : #{JSON.parse(course.body).inspect}======= start date: #{JSON.parse(course.body)["start_at"]}==="
    start_date = JSON.parse(course.body)["start_at"].in_time_zone("Sydney") if JSON.parse(course.body)["start_at"]
    end_date = JSON.parse(course.body)["end_at"].in_time_zone("Sydney") if JSON.parse(course.body)["end_at"]
    create_course({:name => course_name, :course_number => course_id,  :start_date => start_date, :end_date => end_date})
    # This will also be at the admin navigation level, but for now capture data at the student level
    create_profile(course_id)
    @profiles = Profile.all
  end
end

app/helpers/canvas_helper.rb
module CanvasHelper
end

app/views/canvas/page.html.erb
<h1>CODER ATTENDANCE </h1>

<%# if educator you must be able to see all the users %>. 
<%# link to register the card %>


<%# |user name (link) ----- Register Card| %>

<p id="notice"><%= notice %></p>

<h1>Enrollments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Role</th>
      <th>Course</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= link_to profile.user["name"], attendances_path(:profile_id => profile.id) %></td>
        <td><%= profile.role %></td>
        <td><%= link_to 'Register Card Number', new_card_path(:profile_id => profile.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>