config/routes.rb
Rails.application.routes.draw do
  resources :attendances
  resources :cards
  resources :profiles
  resources :courses
  root 'home#page'
  
  # request from canvas LTI
  post '/canvas', to: 'canvas#page'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :card, foreign_key: 'card_opal_number'
  # after_create :calculate_grade
  # after_save :update_canvas_grade

  # self keyword lets us access model methods from controller
  def self.update_checkin(checkin, attendance)
    start_time = "10:00"
    end_time = "17:00"

    attendance.checkin = checkin
    if checkin.in_time_zone('Sydney').strftime("%k:%M %p") <= "10:00"
      attendance.status = "Present"
    elsif checkin.in_time_zone('Sydney').strftime("%k:%M %p").between?(start_time, end_time)
      attendance.status = "Late"
    end
    return attendance
  end

  def self.update_checkout(checkout, attendance)
    puts "UPDATED CHECKOUT====="
    attendance.checkout = checkout
    return attendance
  end

  def calculate_grade
    if self.checkin
          # update grade
      if Attendance.all.count > 0
        # Note: only 60% of the total attendance is give for late status.
        late_pct = 0.6 * ((Attendance.where(:status => "Late").count) / Attendance.all.where.not(checkin: nil).count.to_f)
        present_pct = ((Attendance.where(:status => "Present").count) / Attendance.all.where.not(checkin: nil).count.to_f)
        grade = (present_pct + late_pct) * 100
      end
      self.update_columns(grade: grade)
    end
  end

  def update_canvas_grade

    # fetch course Id and assignment id from canvas as macros (do not hardcode)
    sis_id = self.card.profile.user["sis_user_id"]
    grade = self.grade
    url = "https://coderacademy.instructure.com/api/v1/courses/224/assignments/1420/submissions/sis_user_id:#{sis_id}"
    payload = {"submission": {"posted_grade": grade }}

    if sis_id
      response = HTTParty.put(url, :body => payload.to_json, :headers => { "Content-Type" => 'application/json', "Authorization" => Rails.application.credentials.canvas[:authorization_key]})
    end

  end

end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :set_attendance, only: [:edit, :update, :destroy]

  # GET /attendances
  # GET /attendances.json
  def index
    # UNCOMMENT THIS CODE after hardware test: show the attendance of each user
    # profile.card.attendances
    @profile = Profile.find(params[:profile_id])
    if @profile.card
       @attendances = @profile.card.attendances
    else 
      @attendances = nil
    end
    # @attendances= Attendance.all
  end

  # GET /attendances/1
  # GET /attendances/1.json
  def show
    @profile = Profile.find(params[:profile_id])
    if @profile.card
       @attendances = @profile.card.attendances.where.not(checkout: nil)
    else 
      @attendances = nil
    end
  end

  # GET /attendances/new
  def new
    @attendance = Attendance.new
  end

  # GET /attendances/1/edit
  def edit
  end

  # POST /attendances
  # POST /attendances.json
  def create
    # find the card
    @card = Card.find(attendance_params[:card_opal_number])
    @attendance = Attendance.new(attendance_params)

    # update the attendance status for the first checkin of the day, subsequent tap on are logged just for reference as checkout, but not used for determining the attendance status and grade
    @attendance = @card.attendances.exists?(:date => Date.today.to_s) ? Attendance.update_checkout(params[:time], @attendance) : Attendance.update_checkin(params[:time], @attendance)
    # test code to check if the grade was updated as expected
    # @attendance = Attendance.update_checkin(params[:time], @attendance)
    respond_to do |format|
      if @attendance.save
            # Non nil checkin value, implies this is the first tap for the day, check if an entry exists for previous day, if not found update previous days status to absent 
            # if((@attendance.checkin != nil) &&(!@card.attendances.exists?(:date => Date.yesterday.to_s)))
            #    Attendance.create(:date => Date.yesterday.to_s, :status =>  "Absent", :card_opal_number => @card.opal_number)
            # end
        format.html { redirect_to @attendance, notice: 'Attendance was successfully created.' }
        format.json { render :show, status: :created, location: @attendance }
      else
        format.html { render :new }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attendances/1
  # PATCH/PUT /attendances/1.json
  def update
    respond_to do |format|
      if @attendance.update(attendance_params)
        format.html { redirect_to @attendance, notice: 'Attendance was successfully updated.' }
        format.json { render :show, status: :ok, location: @attendance }
      else
        format.html { render :edit }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendances/1
  # DELETE /attendances/1.json
  def destroy
    @attendance.destroy
    respond_to do |format|
      format.html { redirect_to attendances_url, notice: 'Attendance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attendance
      @attendance = Attendance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attendance_params
      params.require(:attendance).permit(:date, :checkin, :checkout, :status, :grade, :card_opal_number)
    end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/views/attendances/_form.html.erb
<%= form_with(model: attendance, local: true) do |form| %>
  <% if attendance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(attendance.errors.count, "error") %> prohibited this attendance from being saved:</h2>

      <ul>
      <% attendance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :checkin %>
    <%= form.time_select :checkin %>
  </div>

  <div class="field">
    <%= form.label :checkout %>
    <%= form.time_select :checkout %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :grade %>
    <%= form.number_field :grade %>
  </div>

  <div class="field">
    <%= form.label :card_id %>
    <%= form.text_field :card_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/attendances/edit.html.erb
<h1>Editing Attendance</h1>

<%= render 'form', attendance: @attendance %>

<%= link_to 'Show', @attendance %> |
<%= link_to 'Back', attendances_path %>

app/views/attendances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Attendances</h1>

<table class="table">
  <thead>
    <tr>
      <th>Date</th>
      <th>Checkin</th>
      <th>Status</th>
      <th>Grade(%)</th>
      <th>Card</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
   <% if @attendances %>
      <% @attendances.where.not(status: nil).each do |attendance| %>
        <tr>
          <td><%= attendance.date.strftime("%d,%b-%Y")  if attendance.date %></td>
          <td><%= attendance.checkin.strftime("%I:%M %P") if attendance.checkin %></td>
          <td><%= attendance.status %></td>
          <td><%= attendance.grade if attendance.grade %></td>
          <td><%= attendance.card_opal_number %></td>
          <td><%= link_to 'Show', attendance_path(:id => attendance.id, :profile_id => @profile.id) %></td>
          <td><%= link_to 'Edit', edit_attendance_path(attendance) %></td>
          <td><%= link_to 'Destroy', attendance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% else %>
      <p> No attendance logged by the card yet, tap the card or ask your educator or student services to register your card</p>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attendance', new_attendance_path %>

app/views/attendances/new.html.erb
<h1>New Attendance</h1>

<%= render 'form', attendance: @attendance %>

<%= link_to 'Back', attendances_path %>

app/views/attendances/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Attendances</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Checkout</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% if @attendances %>
      <% @attendances.each do |attendance| %>
        <tr>
          <td><%= attendance.date.strftime("%d,%b-%Y")  if attendance.date %></td>
          <td><%= attendance.checkout.strftime("%I:%M %P") if attendance.checkout %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attendance', new_attendance_path %>